FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y build-essential gdb vim valgrind && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /app

# Shell
CMD ["/bin/bash"]
